[project]
name = "workshop2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google>=3.0.0",
    "google-genai>=1.64.0",
    "langchain-text-splitters>=1.1.0",
    "pymupdf>=1.27.1",
]
